---
version: "0.1"
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150
runson: linux
autosplit: true
retryOnFailure: false
maxRetries: 0
concurrency: 10
pre:
  - npm install
  - npx playwright install
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
  type: raw
  mode: dynamic
  command: seq 1 10
testRunnerCommand: npx playwright test tests/loadtest_storyblock.spec.js --shard=$test/10
jobLabel: [playwright-VanillaJS, linux, loadtest, web-vitals]
artifacts:
  name: web-vitals-results
  path:
    - artifacts/loadtest/**/*.json
    - test-results/**/*
