---
version: "0.1"
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150
runson: linux
autosplit: true
retryOnFailure: false
maxRetries: 0
concurrency: 2
pre:
  - npm install
  - npx playwright install
cacheKey: '{{ checksum "package-lock.json" }}'
cacheDirectories:
  - node_modules
testDiscovery:
  type: raw
  mode: dynamic
  command: seq 1 2
testRunnerCommand: npx playwright test tests/loadtest_storyblock.spec.js
jobLabel: [playwright-VanillaJS, linux, loadtest, web-vitals]

report: true
partialReports:
  location: playwright-report
  type: html
  frameworkName: playwright

mergeArtifacts: true
taskIdentifierInNonConflictingArtifacts: true
uploadArtefacts:
  - name: web-vitals-json
    path:
      - artifacts/loadtest/**/*.json
  - name: playwright-report
    path:
      - playwright-report/**/*
  - name: test-results
    path:
      - test-results/**/*
